# Generated by Django 5.2.11 on 2026-02-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
