# Generated by Django 5.2.11 on 2026-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='bound-method-fieldvalue_from_object-of-djangodbmodelsfieldscharfield'),
        ),
    ]
