# Generated by Django 5.2.11 on 2026-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
